version: '3.7'

services:
  app:
    image: hugofabriicio/docker-php
    depends_on:
      - db
      - redis
    volumes:
      - ./:/application:cached

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=app
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: hugofabriicio/docker-nginx
    ports:
      - 80:80
    volumes:
      - ./:/application:cached
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  db-data:
